version: '3.7'
services:
  planner:
    build: ./ToPickPlacePlanner
    secrets:
      - firestore_psw
    ports:
      - 8081:80
    volumes:
      - ./keys:/keys
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/firestore_psw
  api:
    build: ./ToPickPlaceApi
    ports:
      - 8080:8080
    volumes:
      - ./keys:/keys
    environment:
      FIRESTORE_KEY_PATH: /run/secrets/firestore_psw
secrets:
  firestore_psw:
    file: ./keys/topickplace-firestore-client.json
