http:
    routers:
        planner-router:
            rule: "PathPrefix(`/planner`)"
            service: planner
    services:
        planner:
            loadBalancer:
                servers:
                    - url: "http://planner:80/"