http:
    routers:
        planner-router:
            rule: "PathPrefix(`/planner`)"
            service: planner
        api-router:
            rule: "PathPrefix(`/api`)"
            service: api
        ui-router:
            rule: "PathPrefix(`/`)"
            service: ui
    services:
        ui:
            loadBalancer:
                servers:
                    - url: "http://ui:3000/"
        api:
            loadBalancer:
                servers:
                    - url: "http://api:8080/"
        planner:
            loadBalancer:
                servers:
                    - url: "http://planner:80/"
                
