http:
    routers:
        planner-router:
            rule: "PathPrefix(`/planner`)"
            service: planner
            middlewares:
                - planner-remove-prefix
    middlewares:
        planner-remove-prefix:
            stripPrefix:
                prefixes:
                    - "/planner"
    services:
        planner:
            loadBalancer:
                servers:
                    - url: "http://planner:80/"